### ISSUE TITLE
Request: native build for Node.js v12.x runtime

### ISSUE THREAD

**Issue by a-sync** [CherryCircle/lambda-hummus#2]
First of all thank you for this, saved me a lot of time and headache!

As the title says, native build for the latest supported lambda version would be much appreciated.

The error observed when trying to run the current version on Node.js v12.x lambda:
```
Error: The module '/var/task/node_modules/hummus/binding/hummus.node'",
        "was compiled against a different Node.js version using",
        "NODE_MODULE_VERSION 64. This version of Node.js requires",
        "NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
```

Thanks!

**Comment by rsshilli** [comment]
Hello @a-sync ,

Thank you for reporting this issue. We don't have a need here internally yet for v12.x lambda but if you want to submit a PR, that would be great.

Ryan
